language: ruby
rvm:
- 2.1
- 2.2
- 2.3.0
before_install: gem install bundler -v 1.11.2
notifications:
  email:
    - support@travellink.com.au
  flowdock:
    secure: rjxg7hIW69k5k/pAMwx7Z3WKdzeNhBV8EvBoD0U7cQ3j0BdTHCw68FrcqiN/AKQkfVbK4IlytLz0LGAZpQ7eGjSWH0O7W23oOk//hqO8caoYr1V2vF29y6rj92vuSlWMJQ6sBvMSNraAh5Xey/LXHT5Cw1KtZcYIorZBS6lxaKIxC9MMjVx7IIorIdYThpMv7SuvZStG9Ra8hZVD1LNOZtmdcEVT2wD0MyBE2LKtFciZlSDxlPJv38jw5k2xT0hOLJ5L4p8PrFhkiKkg/dt8/RLjt+WWNm0XVo5DDkBB4FHty5iUQcXH5BrCLKutH4+KwaUcF3O2jEMLstxZPWX0mHxjD5QOo2OOu1gAFKXE7jFEy+kXYJB7z1cX2hUb1Sgqn9OGqf2D5020peH2nj+vGOWIq7zKzSWYuGn/uQOVIDkS8YiV5PgrhaFj/ieDlKnk2sQ+vL00ERs/GXpg1lMKuyKasIxydfXoHP8bHUE7R2t5gVsZTLTdYInukVg9wFA0S2I09WvyUiQxniP7ljTcqigD+O+NuHGTPga+IJM9jpB/ZHuha2jC0omkR96/dvlhDZtBlnXB88N5kfFFYbaT2a1erYvwBTuVY8QueIv7V3kOmu6pCMTcnR8DNoekzpi3dLQwW8rifu+6MsuLaxsywd8JJmNJQDGxU4CSV5yQUl4=
sudo: false
cache: bundler
